apiVersion: v1
kind: Service
metadata:
  name: mfa-start
  namespace: default   # 写上更明确一点，跟你现在用的命名空间一致
spec:
  type: NodePort
  selector:
    app: mfa-start
  ports:
    - name: http
      port: 9999        # cluster 内部访问用的端口
      targetPort: 9999  # Pod里容器实际上监听的端口
      nodePort: 30099   # 外面访问用的端口
